### ISSUE TITLE
Overriding the default provider with table doesn't work

### ISSUE THREAD

**Issue by cameronr** [bwpge/lualine-pretty-path#2]
First, great plugin! I was just about to write a lazyvim filename plugin for lualine but I'm glad I searched for something existing first!

I want to override the default provider but it doesn't work when I pass in my own module as table (as opposed to a string) because there's no return from ’utils.require_provider` when the user passes in a table so it ends up just returning nil:

https://github.com/bwpge/lualine-pretty-path/blob/51873c2ea8e70843b7599913a64eabfbbd5b980a/lua/lualine-pretty-path/utils.lua#L64-L84

There are also a few other minor things that prevent `pretty_path._default_provider` from getting set correctly.

I'll submit a PR shortly.

**Comment by bwpge** [comment]
Great catch, I definitely didn't test the default provider override stuff very well.

Thanks for taking the time to open an issue and work on a fix!
